# TCL File Generated by Component Editor 22.1
# Wed May 13 04:45:41 EDT 2026
# DO NOT MODIFY


# 
# hft_sim "HFT_SIM" v1.0
#  2026.05.13.04:45:41
# HFT pipeline Avalon-MM peripheral
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hft_sim
# 
set_module_property DESCRIPTION "HFT pipeline Avalon-MM peripheral"
set_module_property NAME hft_sim
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME HFT_SIM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL HFT_SIM
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file HFT_SIM.sv SYSTEM_VERILOG PATH HFT_SIM.sv TOP_LEVEL_FILE
add_fileset_file sys_def.svh SYSTEM_VERILOG PATH sys_def.svh
add_fileset_file dispatch_fifo_bram.sv SYSTEM_VERILOG PATH dispatcher/dispatch_fifo_bram.sv
add_fileset_file order_dispatcher.sv SYSTEM_VERILOG PATH dispatcher/order_dispatcher.sv
add_fileset_file heap_fsm.sv SYSTEM_VERILOG PATH heap_engine/heap_fsm.sv
add_fileset_file symbol_engine.sv SYSTEM_VERILOG PATH heap_engine/symbol_engine.sv
add_fileset_file arbiter.sv SYSTEM_VERILOG PATH mmu/arbiter.sv
add_fileset_file HPTW.sv SYSTEM_VERILOG PATH mmu/HPTW.sv
add_fileset_file mem_bank.sv SYSTEM_VERILOG PATH mmu/mem_bank.sv
add_fileset_file mmu.sv SYSTEM_VERILOG PATH mmu/mmu.sv
add_fileset_file trade_aggregator.sv SYSTEM_VERILOG PATH trade_log/trade_aggregator.sv
add_fileset_file trade_log.sv SYSTEM_VERILOG PATH trade_log/trade_log.sv
add_fileset_file hex7seg.sv SYSTEM_VERILOG PATH soc_io/hex7seg.sv


# 
# parameters
# 
add_parameter TRADE_LOG_DEPTH INTEGER 1024 ""
set_parameter_property TRADE_LOG_DEPTH DEFAULT_VALUE 1024
set_parameter_property TRADE_LOG_DEPTH DISPLAY_NAME TRADE_LOG_DEPTH
set_parameter_property TRADE_LOG_DEPTH WIDTH ""
set_parameter_property TRADE_LOG_DEPTH TYPE INTEGER
set_parameter_property TRADE_LOG_DEPTH UNITS None
set_parameter_property TRADE_LOG_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TRADE_LOG_DEPTH DESCRIPTION ""
set_parameter_property TRADE_LOG_DEPTH HDL_PARAMETER true


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group HFT_SIM
set_module_assignment embeddedsw.dts.name HFT_SIM
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 address address Input 5
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point soc_io
# 
add_interface soc_io conduit end
set_interface_property soc_io associatedClock clock
set_interface_property soc_io associatedReset ""
set_interface_property soc_io ENABLED true
set_interface_property soc_io EXPORT_OF ""
set_interface_property soc_io PORT_NAME_MAP ""
set_interface_property soc_io CMSIS_SVD_VARIABLES ""
set_interface_property soc_io SVD_ADDRESS_GROUP ""

add_interface_port soc_io HEX0 hex0 Output 7
add_interface_port soc_io HEX1 hex1 Output 7
add_interface_port soc_io HEX2 hex2 Output 7
add_interface_port soc_io HEX3 hex3 Output 7
add_interface_port soc_io HEX4 hex4 Output 7
add_interface_port soc_io HEX5 hex5 Output 7
add_interface_port soc_io KEY key Input 4

